[workspace]
authors = ["Tim de Jager <tim@prefix.dev>"]
channels = ["https://prefix.dev/conda-forge"]
name = "our-game"
platforms = ["osx-arm64", "linux-64", "win-64"]
version = "0.1.0"

[tasks]
start = "love ."

[dependencies]
love2d = ">=11.5,<12"
